// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCochQ31m402d57HwAlkzGU6Iujt3MKX1E',
    appId: '1:531141142742:web:56656380053e0f179ec177',
    messagingSenderId: '531141142742',
    projectId: 'final-project-203a5',
    authDomain: 'final-project-203a5.firebaseapp.com',
    storageBucket: 'final-project-203a5.appspot.com',
    measurementId: 'G-GCJVVYW4P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc_jr2QjRuQ5frOqhx_Th9lZZ4MJD7RTc',
    appId: '1:531141142742:android:defe759e853805c59ec177',
    messagingSenderId: '531141142742',
    projectId: 'final-project-203a5',
    storageBucket: 'final-project-203a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv3ko0hS9R8GsqLEv57KvzripdzuVwxls',
    appId: '1:531141142742:ios:a27059b75e5aa7839ec177',
    messagingSenderId: '531141142742',
    projectId: 'final-project-203a5',
    storageBucket: 'final-project-203a5.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv3ko0hS9R8GsqLEv57KvzripdzuVwxls',
    appId: '1:531141142742:ios:a27059b75e5aa7839ec177',
    messagingSenderId: '531141142742',
    projectId: 'final-project-203a5',
    storageBucket: 'final-project-203a5.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );
}
